[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_escrow = "5NvfRXc42KPJCVFcRAK1vh59ZFEd19jcUB7pox9fntgx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/kunal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
